```
FROM registry.cn-beijing.aliyuncs.com/uhongedu/basic_v2:2.0

# 升级pip
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --upgrade pip setuptools \
	# 资源SDK
	&& pip install -i --trusted-host http://pypi.uhongedu.com/packages/ziyuan_sdk-0.0.18.tar.gz \
		# ucm
		http://pypi.uhongedu.com/packages/ucm_sdk-0.0.1.tar.gz \
		# aly日志
		http://pypi.uhongedu.com/packages/yh_sls-0.0.5.tar.gz \
		http://pypi.uhongedu.com/packages/yh_sdk-0.0.4.tar.gz \
	# Python 新的 disribution
	&& pip install -i https://mirrors.aliyun.com/pypi/simple/ wheel \
	# 第三方库安装
	&& pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ \
		# 数据库连接引擎
		PyMySQL==0.8.0 \
		# jsonfield
		jsonfield==2.0.2 \
		# django
		Django==2.0.4 \
		django-crontab==0.7.1 \
		# Redis
		redis==2.10.6 \
		# oss2
		oss2==2.4.0 \
		aliyunsdkcore==1.0.2 \
		aliyun-python-sdk-sts==3.0.0 \
		# celery
		celery==4.1.0 \
		# 序列化
		msgpack==0.5.6 \
		# kombu
		kombu==4.2.0 \
		xlrd==1.1.0 \
		xlwt==1.3.0 \
		# pypinyin
		pypinyin==0.30.0 \
		# 异步请求
		grequests==0.3.0 \
		# yaml
		PyYAML==3.12 \
		# uwsgi
		uwsgi==2.0.17 \
		# 代码分析工具
		# 安装 line-profiler 需要使用
		Cython==0.29.14 \
		line_profiler==3.1.0 \
		memory-profiler==0.52.0 \
		# memcache
		python-memcached==1.57 \
		# redis
		django-redis==4.10.0 \
		# Twisted
		Twisted==18.4.0 \
		# 阿里云日志
		aliyun-log-python-sdk==0.6.30.4 \
		uwsgidecorators==1.1.0 \
        # excel
		xlsxwriter==1.0.9 \
		# python-alipay-sdk
		python-alipay-sdk==1.7.1 \
		# weixin
		weixinpy==0.0.9 \
		# orm
		orator==0.9.7 \
		# cmd
		fire==0.1.3 \
		# https://github.com/ipipdotnet/datx-python
		ipip-datx \
		# 消息服务mqtt
		paho-mqtt==1.4.0 \
		# 阿里云ACM配置中心 
		acm-sdk-python \
		apscheduler==3.5.3 \
		aliyun-python-sdk-core==2.13.20 \
        aliyun-python-sdk-core-v3==2.13.11 \
        # 阿里云推送
        aliyun-python-sdk-push==3.13.3 \
		# 敏感词过滤
		aliyun-python-sdk-green==3.5.1 \
		# 钉钉
		dingtalk-sdk==1.3.8 \
		aliyun-python-sdk-dysmsapi==1.0.0 \
		# python 操作 gitlab
        python-gitlab==1.9.0 \
		# Python的非验证SQL解析器
        sqlparse===0.3.1 \
		# Token 认证机制
        PyJWT===1.7.1 \
		# Python 调试用
		PySnooper===0.4.2 \
		# DES、Triple DES 加密
		pyDes===2.0.1 \
	&& rm -rf /var/lib/apt/lists/*
```